plugins {
    id 'io.github.qigao.simpledsl.java'
}

simpledsl {
    springLibrary()
    persistence {
        jooq()
    }
    lombok()
    dependency('api', 'jakarta-validation')
}

dependencies {
    implementation project(':shared-utils')
    api project(':music-json')
    implementation project(':music-entity')
}
