plugins {
    id 'durex.spring-library'
}

durex {
    persistence {
        jooq()
    }
    lombok()
}

dependencies {
    implementation project(':shared-utils')
    api project(':music-json')
    implementation project(':music-entity')
    compileOnly durex.library('javax-cdi')
    compileOnly durex.library('javax-inject')
    compileOnly durex.library('javax-validation')
}
