import static groovy.io.FileType.DIRECTORIES
import static groovy.io.FileVisitResult.SKIP_SUBTREE

def skipDirs = ~/^(build|\..*|src|target)/
def infrastructureDirs = ['build-bootstrap', 'build-logic', 'migration', 'reference'] as Set

def isExcludedDir = { File dir ->
    skipDirs.matcher(dir.name).matches() ||
            (dir.parentFile == rootDir && infrastructureDirs.contains(dir.name))
}

def preDir = {
    if (isExcludedDir(it))
        return SKIP_SUBTREE
}

def getProjectName(String dir) {
    return (dir - (rootDir.toString() + "/")).replaceAll("/", ":")
}

rootDir.traverse(
        type: DIRECTORIES,
        preDir: preDir) { dir ->
    def dstr = dir.toString()
    if (!isExcludedDir(dir) &&
            new File(dstr + "/build.gradle").exists()) {
        include getProjectName(dstr)
    }
}
