pluginManagement {
    includeBuild('build-bootstrap')
    includeBuild('build-logic')
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'durex.settings'
}

rootProject.name = 'durex'

durexSettings {
    repositoryRoot.set(layout.settingsDirectory)
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}
