plugins {
    id 'durex.spring-library'
    id 'org.jsonschema2pojo'
}

durex {
    dependency('api', 'jackson-annotations')
    dependency('api', 'jackson-databind')
    dependency('api', 'jakarta-validation')
}

jsonSchema2Pojo {
    targetPackage = 'com.github.durex.music.model'
    source = files("$projectDir/json")
    includeJsr303Annotations = true
    useJakartaValidation = true
    includeGetters = true
    includeSetters = true
    includeToString = true
    includeHashcodeAndEquals = true
    generateBuilders = true
}
