plugins {
    id 'io.github.qigao.simpledsl.java'
}

simpledsl {
    springLibrary()
    dependency('api', 'jackson-annotations')
    dependency('api', 'jackson-databind')
    dependency('api', 'jakarta-validation')
    jsonSchema()
}

simpledslJsonSchema {
    source = 'json'
    packageName = 'com.github.durex.music.model'
    validation = true
    builders = true
}
