# versions for libraries
[versions]
lombok = '6.3.0'
querydsl = '5.0.0'
# Libs config
[libraries]

# Groups
commons-lang3 = { group = 'org.apache.commons', name = 'commons-lang3', version = { strictly = '[3.8, 4.0[', prefer = '3.9' } }
commons-io = { group = 'commons-io', name = 'commons-io', version = '2.11.0' }
commons-http = { group = 'org.apache.httpcomponents', name = 'httpclient', version = { strictly = '[4.5, 5.0[', prefer = '4.5.2' } }
commons-httpclient = { group = 'org.apache.httpcomponents', name = 'httpclient', version = { strictly = '[4.5, 5.0[', prefer = '4.5.2' } }
ok-http = { group = 'com.squareup.okhttp', name = 'okhttp', version = '2.7.5' }

mybatis-generator = { group = 'org.mybatis.generator', name = 'mybatis-generator', version = '1.3.6' }

# exceptions
unchecked = { group = 'com.pivovarit', name = 'throwing-function', version = '1.5.1' }

# Ser/De
validation = { group = 'javax.validation', name = 'validation-api', version = '2.0.1.Final' }
jackson-bom = { group = 'com.fasterxml.jackson', name = 'jackson-bom', version = '2.12.5' }
fastjson = { group = 'com.alibaba', name = 'fastjson', version = '1.2.47' }

slf4j = { group = 'org.slf4j', name = 'slf4j-api', version = '1.7.32' }
logback = { group = 'ch.qos.logback', name = 'logback-classic', version = '1.2.8' }
# Id generator
uuid = { group = 'com.github.f4b6a3', name = 'uuid-creator', version = '4.1.3' }
ulid = { group = 'com.github.f4b6a3', name = 'ulid-creator', version = '4.1.2' }
tsid = { group = 'com.github.f4b6a3', name = 'tsid-creator', version = '4.1.1' }
ksuid = { group = 'com.github.f4b6a3', name = 'ksuid-creator', version = '2.2.0' }

lombok = { group = 'org.projectlombok', name = 'lombok', version = '1.18.22' }
querydsl-apt = { group = 'com.querydsl', name = 'querydsl-apt', version.ref = 'querydsl' }
querydsl-core = { group = 'com.querydsl', name = 'querydsl-core', version.ref = 'querydsl' }
querydsl-jpa = { group = 'com.querydsl', name = 'querydsl-jpa', version.ref = 'querydsl' }
[bundles]
commons = ['commons-lang3', 'commons-io']
idCreator = ['uuid', 'ulid', 'tsid', 'ksuid']
querydsl = ['querydsl-apt', 'querydsl-core', 'querydsl-jpa']
# Gradle plugins config
[plugins]
lombok = { id = 'io.freefair.lombok', version.ref = 'lombok' }
