# versions for libraries
[versions]
quarkus = "2.2.3.Final"

# Libs config
[libraries]
quarkus-bom = {group = 'io.quarkus.platform', name = 'quarkus-bom', version.ref = 'quarkus'}

# Gradle plugins config
[plugins]
quarkus = {id = 'io.quarkus', version.ref = 'quarkus'}
