version: "3.7"

services:
  db:
    image: mariadb:10.4.8
    container_name: db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=music
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db
    ports:
      - 8260:8080
    hostname: app
    depends_on:
      - db
