# versions for libraries
[versions]
lombok = '6.3.0'
jackson = "2.13.3"
jakarta = "9.1.0"

# Libs config
[libraries]

# Groups
commons-lang3 = { group = 'org.apache.commons', name = 'commons-lang3', version = { strictly = '[3.8, 4.0[', prefer = '3.9' } }
commons-io = { group = 'commons-io', name = 'commons-io', version = '2.11.0' }
commons-http = { group = 'org.apache.httpcomponents', name = 'httpclient', version = { strictly = '[4.5, 5.0[', prefer = '4.5.2' } }
commons-httpclient = { group = 'org.apache.httpcomponents', name = 'httpclient', version = { strictly = '[4.5, 5.0[', prefer = '4.5.2' } }
commons-text = { group = 'org.apache.commons', name = 'commons-text', version = '1.9' }
commons-collections4 = { group = 'org.apache.commons', name = 'commons-collections4', version = { strictly = '[4.4, 5.0[' } }
ok-http = { group = 'com.squareup.okhttp', name = 'okhttp', version = '2.7.5' }
# exceptions
unchecked = { group = 'com.pivovarit', name = 'throwing-function', version = '1.5.1' }

#Jackson Ser/De
validation = { group = 'javax.validation', name = 'validation-api', version = '2.0.1.Final' }
jackson-bom = { group = 'com.fasterxml.jackson', name = 'jackson-bom', version.ref = 'jackson' }

slf4j = { group = 'org.slf4j', name = 'slf4j-api', version = '1.7.36' }
logback = { group = 'ch.qos.logback', name = 'logback-classic', version = '1.2.11' }
logstash = { group = 'net.logstash.logback', name = 'logstash-logback-encoder', version = '7.2' }

# Id generator
uuid = { group = 'com.github.f4b6a3', name = 'uuid-creator', version = '4.1.3' }
ulid = { group = 'com.github.f4b6a3', name = 'ulid-creator', version = '4.1.2' }
tsid = { group = 'com.github.f4b6a3', name = 'tsid-creator', version = '4.1.1' }
ksuid = { group = 'com.github.f4b6a3', name = 'ksuid-creator', version = '2.2.0' }

reactor-core = { group = 'io.projectreactor', name = 'reactor-core', version = '3.4.18' }

jakarta-bom = { group = 'jakarta.platform', name = 'jakarta.jakartaee-bom', version.ref = 'jakarta' }
jboss-spec-jaxrs = { group = 'org.jboss.spec.javax.ws.rs', name = 'jboss-jaxrs-api_2.1_spec', version = '2.0.2.Final' }
# Google
guava = { group = 'com.google.guava', name = 'guava', version = '31.1-jre' }
[bundles]
commons = ['commons-lang3', 'commons-io', 'commons-text', 'commons-collections4']
idCreator = ['uuid', 'ulid', 'tsid', 'ksuid']

# Gradle plugins config
[plugins]
lombok = { id = 'io.freefair.lombok', version.ref = 'lombok' }
