# versions for libraries
[versions]
# version for spring
springboot = "2.6.6"
spring-bom = "1.0.11.RELEASE"

# Libs config
[libraries]

[bundles]


# Gradle plugins config
[plugins]
spring-bom = { id = "io.spring.dependency-management", version.ref = "spring-bom" }
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
