# versions for libraries
[versions]
junit = "5.8.2"
equalsverifier = "3.7.2"
wiremock = "2.31.0"
rest-assured = "4.4.0"
to-string-verifier = "1.4.8"
h2 = "1.4.200"
testcontainers = "1.17.1"
# Libs config
[libraries]
h2db = { group = "com.h2database", name = "h2", version.ref = "h2" }

# Test
junit5-bom = { group = 'org.junit', name = 'junit-bom', version.ref = 'junit' }
equalsverifier = { module = 'nl.jqno.equalsverifier:equalsverifier', version.ref = 'equalsverifier' }
wiremock = { group = 'com.github.tomakehurst', name = 'wiremock-jre8', version.ref = 'wiremock' }
rest-assured = { group = 'io.rest-assured', name = 'rest-assured', version.ref = 'rest-assured' }
jparams = { group = 'com.jparams', name = 'to-string-verifier', version.ref = 'to-string-verifier' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version = '2.2' }
hamcrest-date = { group = 'org.exparity', name = 'hamcrest-date', version = '2.0.7' }
test-containers-bom = { group = 'org.testcontainers', name = 'testcontainers-bom', version.ref = 'testcontainers' }
api-guardian = { group = 'org.apiguardian', name = 'apiguardian-api', version = '1.1.2' }
