name: 'Env Action'
description: 'Share Variables from action'
outputs:
  sonar_key:
    description: "sonar key"
    value: ${{ steps.vars.outputs.SONAR_KEY }}
runs:
  using: "composite"
  steps:
    - name: set env vars from PR
      id: vars
      env:
        PUSH_TO_MASTER: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        if ${PUSH_TO_MASTER} == true; then
           echo "::set-output name=SONAR_KEY::-Dsonar.branch.name=master"
           echo "merge code to master"
        else
           echo "::set-output name=SONAR_KEY::-Dsonar.pullrequest.key=${{ github.event.pull_request.number}}"
           echo "push code to pull_request"
        fi
      shell: bash
