plugins {
    id 'java-library'
}

def gradleCatalog = extensions.getByType(org.gradle.api.artifacts.VersionCatalogsExtension).named('gLibs')
def lombok = gradleCatalog.findLibrary('lombok-modern').get()

dependencies {
    implementation dbLibs.jooq.spring.codegen
    implementation dbLibs.jooq.spring.meta
    compileOnly lombok
    annotationProcessor lombok
}
