pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.github.qigao.simpledsl.settings' version '0.3.0'
}

rootProject.name = 'spring-messaging-migration'

simpledslSettings {
    repositoryRoot.set(layout.settingsDirectory.dir('../..'))
    modulesManifest.set(layout.settingsDirectory.file('modules.toml'))
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}
