plugins {
    id 'durex.java-library'
    id 'durex.jooq-schema'
}

sourceSets {
    main {
        java {
            exclude 'com/github/durex/music/support/DemoMusicData.java'
        }
    }
}

durex {
    lombok()
}

dependencies {
    api project(':music-json')
}

durexJooq {
    source = 'database/schema/mysql.sql'
    packageName = 'com.github.durex.model'
}
