import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.ModuleKind
import com.github.durex.gradle.model.DurexModuleModel

plugins { id 'durex.module' }

def model = extensions.getByType(DurexModuleModel)
model.requireFeature('durex.feature.redis', project.path, ModuleKind.SPRING_LIBRARY, ModuleKind.SPRING_SERVICE)
model.enableCapability('redis')
DurexDependencyAccess.add(project, model, 'implementation', 'spring-redis')
