import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.model.DurexModuleModel

plugins { id 'durex.module' }

def model = extensions.getByType(DurexModuleModel)
model.enableCapability('lombok')
DurexDependencyAccess.add(project, model, 'compileOnly', 'lombok')
DurexDependencyAccess.add(project, model, 'annotationProcessor', 'lombok')
