import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.DurexModuleState

plugins { id 'durex.module' }

def state = extensions.getByType(DurexModuleState)
state.activateFeature('lombok')
DurexDependencyAccess.add(project, state, 'compileOnly', 'lombok')
DurexDependencyAccess.add(project, state, 'annotationProcessor', 'lombok')
