import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.ModuleKind
import com.github.durex.gradle.model.DurexModuleModel

plugins {
    id 'java-library'
    id 'durex.internal.java-base'
}

def model = extensions.getByType(DurexModuleModel)
model.claim(ModuleKind.JAVA_LIBRARY, project.path)
DurexDependencyAccess.add(project, model, 'testImplementation', 'junit-jupiter')
DurexDependencyAccess.add(project, model, 'testRuntimeOnly', 'junit-platform-launcher')

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
