import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.DurexModuleState
import com.github.durex.gradle.ModuleKind

plugins {
    id 'java-library'
    id 'durex.spring-base'
}

def state = extensions.getByType(DurexModuleState)
state.claim(ModuleKind.SPRING_LIBRARY)
DurexDependencyAccess.add(project, state, 'implementation', 'spring-core')
DurexDependencyAccess.add(project, state, 'testImplementation', 'spring-test')

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
