import com.github.durex.gradle.ModuleKind
import com.github.durex.gradle.model.DurexModuleModel

plugins { id 'durex.module' }

def model = extensions.getByType(DurexModuleModel)
model.requireFeature('durex.feature.native', project.path, ModuleKind.SPRING_SERVICE)
pluginManager.apply('org.graalvm.buildtools.native')
model.enableCapability('native')
