import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.model.DurexModuleModel

plugins {
    id 'durex.java-base'
}

def model = extensions.getByType(DurexModuleModel)
['implementation', 'api', 'testImplementation'].findAll { configuration ->
    configurations.findByName(configuration) != null
}.each { configuration ->
    DurexDependencyAccess.activatePlatform(project, model, configuration, 'spring')
}
