import com.github.durex.gradle.DurexModuleState
import com.github.durex.gradle.ModuleKind

plugins { id 'durex.module' }

def state = extensions.getByType(DurexModuleState)
state.requireFeature('durex.feature.native', ModuleKind.SPRING_SERVICE)
pluginManager.apply('org.graalvm.buildtools.native')
state.activateFeature('native')
state.enableNative()
