import com.github.durex.gradle.DurexDependencyAccess
import com.github.durex.gradle.ModuleKind
import com.github.durex.gradle.model.DurexModuleModel

plugins {
    id 'org.springframework.boot'
    id 'durex.internal.spring-base'
}

def model = extensions.getByType(DurexModuleModel)
model.claim(ModuleKind.SPRING_SERVICE, project.path)
DurexDependencyAccess.add(project, model, 'implementation', 'spring-core')
DurexDependencyAccess.add(project, model, 'testImplementation', 'spring-test')
DurexDependencyAccess.add(project, model, 'testRuntimeOnly', 'junit-platform-launcher')

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
