[versions]
junit = "5.8.2"

[libraries.junit-jupiter]
module = "org.junit.jupiter:junit-jupiter"
version.ref = "junit"

[libraries.junit-platform-launcher]
module = "org.junit.platform:junit-platform-launcher"
version = "1.8.2"
