name: 'Cache Action'
description: 'Cache everything'
runs:
  using: "composite"
  steps:
    - name: Cache Build
      uses: actions/cache@v2
      id: restore-build
      with:
        path: |
          ~/.gradle/*
          ${{ github.workspace }}
        key: gradle-${{ github.run_id }}-${{ github.run_number }}
