plugins {
    id 'durex.java-library'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            include 'com/github/durex/shared/annotation/NullChecker.java'
            include 'com/github/durex/shared/annotation/ValueChecker.java'
            include 'com/github/durex/shared/exceptions/ApiException.java'
            include 'com/github/durex/shared/exceptions/model/**'
            include 'com/github/durex/shared/model/**'
            include 'com/github/durex/shared/support/**'
        }
    }
}

durex {
    lombok()
}

dependencies {
    compileOnly durex.library('javax-cdi')
    compileOnly durex.library('javax-interceptor')
    compileOnly durex.library('javax-validation')
}
