pluginManagement {
    includeBuild('../..')
    repositories { gradlePluginPortal(); mavenCentral() }
}
plugins { id 'durex.settings' }

durexSettings {
    repositoryRoot.set(file('.'))
    dependencyManifest.set(file('../../../gradle/dependencies/durex.toml'))
}

rootProject.name = 'modules-auto-spring-no-manifest'
