pluginManagement {
    includeBuild('../..')
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
plugins {
    id 'durex.settings'
}

def manifestName = providers.gradleProperty('manifest').orElse('valid.toml')
durexSettings {
    repositoryRoot.set(file('../../..'))
    dependencyManifest.set(file(manifestName.get()))
    moduleDiscovery.set(false)
}

rootProject.name = 'manifest-validation'
