plugins { id 'durex.spring-library' }

import com.github.durex.gradle.model.DurexModuleModel

durex {
    dependency('api', 'jackson-annotations')
    dependency('api', 'jackson-databind')
    dependency('implementation', 'spring-jooq')
}

def model = extensions.getByType(DurexModuleModel)
assert model.platformBindings.get().contains('api:spring')
assert model.platformBindings.get().contains('implementation:spring')
assert configurations.api.dependencies.findAll {
    it.group == 'org.springframework.boot' && it.name == 'spring-boot-dependencies'
}.size() == 1

tasks.register('verifyDependencyBindings')
