plugins {
  alias qLibs.plugins.quarkus
}

dependencies {
  implementation project(':core:shared:utils')
  implementation project(':core:schema:music:json')
  implementation project(':core:schema:music:entity')
  implementation project(':core:schema:music:repo')
  implementation project(':core:shared:jakarta:common')
  implementation project(':core:shared:jakarta:config')
  implementation project(':core:shared:jakarta:imperative')
  implementation 'io.quarkus:quarkus-smallrye-openapi'
  implementation 'io.quarkus:quarkus-smallrye-health'
  testImplementation 'io.quarkus:quarkus-jacoco'
}

apply from: "$rootDir/gradle/library/quarkus-core.gradle"
apply from: "$rootDir/gradle/library/quarkus-test.gradle"
apply from: "$rootDir/gradle/library/quarkus-imperative.gradle"


