plugins {
    alias sLibs.plugins.springboot4
}

def repoRoot = gradle.ext.repoRoot
def gradleCatalog = extensions.getByType(org.gradle.api.artifacts.VersionCatalogsExtension).named('gLibs')
def lombok = gradleCatalog.findLibrary('lombok-modern').get()

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir 'src/spring/java'
            exclude 'com/github/durex/music/controller/**'
            exclude 'com/github/durex/music/config/**'
        }
    }
    test {
        java {
            setSrcDirs(['src/springTest/java'])
        }
        resources {
            setSrcDirs(['src/springTest/resources'])
        }
    }
}

dependencies {
    implementation project(':shared-common')
    implementation project(':shared-utils')
    implementation project(':music-json')
    implementation project(':music-entity')
    implementation project(':music-repo')
    compileOnly 'javax.enterprise:cdi-api:2.0.SP1'
    compileOnly 'javax.inject:javax.inject:1'
    compileOnly 'javax.transaction:javax.transaction-api:1.3'
    compileOnly lombok
    annotationProcessor lombok
    testRuntimeOnly 'com.h2database:h2'
}

apply from: new File(repoRoot, 'gradle/library/spring-core.gradle')
apply from: new File(repoRoot, 'gradle/library/spring-web.gradle')
apply from: new File(repoRoot, 'gradle/library/spring-test.gradle')
apply from: new File(repoRoot, 'gradle/library/spring-web-test.gradle')
apply from: new File(repoRoot, 'gradle/library/spring-observability.gradle')
