plugins {
    id 'durex.spring-service'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir 'src/spring/java'
            exclude 'com/github/durex/music/controller/**'
            exclude 'com/github/durex/music/config/**'
        }
    }
    test {
        java {
            setSrcDirs(['src/springTest/java'])
        }
        resources {
            setSrcDirs(['src/springTest/resources'])
        }
    }
}

durex {
    persistence {
        jooq()
    }
    web()
    aop()
    transaction()
    lombok()
    dependency('testRuntimeOnly', 'h2')
}

dependencies {
    implementation project(':shared-common')
    implementation project(':shared-spring-interceptor')
    implementation project(':shared-utils')
    implementation project(':music-json')
    implementation project(':music-entity')
    implementation project(':music-repo')
    implementation project(':music-api')
}
