name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '30 1 * * 1' # 01:30 on Monday UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: $
          expire-in: 7days # Set this to 0 to delete all artifacts
