name: Run Gradle on PRs and Pushes
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          check-latest: true
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: run gradle assemble
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assemble
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: run test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  integrationTest:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: run integration test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: integrationTest
  sonarcloud:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
