name: Run Gradle on PRs and Pushes
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64
      - name: CheckOut and Cache dependenices
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: |
            ~/.gradle/caches
            gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: run gradle assemble
        run: ./gradlew assemble
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run gradle test
        run: ./gradlew test

  integrationTest:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: run integration test
        run: ./gradlew integrationTest

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
