name: Quarkus Starter Project Validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
      - uses: ./.github/workflows/templates/cache-cation
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/templates/cache-cation
      - name: run gradle assemble
        run: ./gradlew quarkus:starter:assemble
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/templates/cache-cation
      - name: Validate Code
        run: ./gradlew quarkus:starter:check
  sonar:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/templates/cache-cation
      - id: sonar_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew quarkus:starter:sonarqube -Dsonar.organization=power-durex-app ${{ steps.sonar_vars.outputs.sonar_key }} --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  integrationTest:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/templates/cache-cation
      - name: run integration test
        run: ./gradlew quarkus:starter:integrationTest

