name: Quarkus Starter Project
on:
  push:
    branches:
      - master
    paths:
      - 'core/music/**'
      - '.github/workflows/quarkus-starter.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'core/music/**'
      - '.github/workflows/quarkus-starter.yml'
env:
  DATABASE_USERNAME: music
  DATABASE_PASSWORD: secret
  DATABASE_PORT: 3306
  DATABASE_NAME: music
  DATABASE_HOST: localhost
jobs:
  setup:
    name: Setup Java Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action

  check:
    name: Check Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: generate schema
        run: ./gradlew core:shared:schema:music:repo:generateJooq
      - name: run gradle assemble
        run: ./gradlew core:music:assemble -DDATABASE_USERNAME="$DATABASE_USERNAME" -DDATABASE_PASSWORD="$DATABASE_PASSWORD" -DDATABASE_PORT="$DATABASE_PORT" -DDATABASE_NAME="$DATABASE_NAME" -DDATABASE_HOST="$DATABASE_HOST"
      - name: Execute Related Check tasks
        run: ./gradlew core:music:check
      - name: Validate Code Coverage
        run: ./gradlew core:music:jacocoTestCoverageVerification
      - id: pr_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew core:music:sonarqube -Dsonar.organization=power-durex-app ${{ steps.pr_vars.outputs.sonar_key }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
