name: Quarkus Starter Project
on:
  push:
    branches:
      - master
    paths:
      - 'quarkus/starter/**'
      - '.github/workflows/quarkus-starter.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'quarkus/starter/**'
      - '.github/workflows/quarkus-starter.yml'

jobs:
  setup:
    name: Setup Java Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action

  build:
    name: Build Quarkus Starter Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: run gradle assemble
        run: ./gradlew quarkus:starter:assemble

  check:
    name: Check Quarkus Starter Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Execute Related Check tasks
        run: ./gradlew quarkus:starter:check
      - name: Validate Code Coverage
        run: ./gradlew quarkus:starter:jacocoTestCoverageVerification
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: quarkus/starter/build
          key:  ${{ runner.os }}-gradle-build-quarkus-starter-project
  sonar:
    name: Sonar Analisys
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: quarkus/starter/build
          key:  ${{ runner.os }}-gradle-build-quarkus-starter-project
      - id: pr_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew quarkus:starter:sonarqube -Dsonar.organization=power-durex-app ${{ steps.pr_vars.outputs.sonar_key }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  IT:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: quarkus/starter/build
          key:  ${{ runner.os }}-gradle-build-quarkus-starter-project
      - name: run integration test
        run: ./gradlew quarkus:starter:integrationTest
