name: Quarkus Starter Project
on:
  push:
    branches:
      - master
    paths:
      - 'core/music/**'
      - '.github/workflows/quarkus-starter.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'core/music/**'
      - '.github/workflows/quarkus-starter.yml'
env:
  DATABASE_USERNAME: music
  DATABASE_PASSWORD: secret
  DATABASE_PORT: 3306
  DATABASE_NAME: music
  DATABASE_HOST: localhost
jobs:
  check:
    name: Check Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java Project
        uses: ./.github/workflows/templates/config-action
      - name: compile annotation
        run: ./gradlew core:shared:json-schema-annotation:build
      - name: generate schema
        run: ./gradlew core:schema:music:entity:generateJooq
      - name: run gradle assemble
        run: ./gradlew core:music:assemble -DDATABASE_USERNAME="$DATABASE_USERNAME" -DDATABASE_PASSWORD="$DATABASE_PASSWORD" -DDATABASE_PORT="$DATABASE_PORT" -DDATABASE_NAME="$DATABASE_NAME" -DDATABASE_HOST="$DATABASE_HOST"
      - name: Execute Related Check tasks
        run: ./gradlew core:music:check
      - name: Validate Code Coverage
        run: ./gradlew core:music:jacocoTestCoverageVerification
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: core/music
          key:  ${{ runner.os }}-gradle-build-quarkus-project-${{ github.run_id }}
