name: Quarkus Starter Project Validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: run gradle assemble
        run: ./gradlew quarkus:starter:assemble
  test:
    needs: [ setup,build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Analyze with SonarCloud
        run: ./gradlew quarkus:starter:check sonarqube -Dsonar.organization=power-durex-app -Dsonar.pullrequest.key=${{github.event.pull_request.number}} --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  integrationTest:
    needs: [ setup,test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/cache@v2
        id: restore-build
        with:
          path: ./*
          key:
            ${{ github.sha }}
      - name: run integration test
        run: ./gradlew quarkus:starter:integrationTest

