name: Quarkus Starter Project Validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.sonar/cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.sonar/cache
            quarkus/starter/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: run gradle assemble
        run: ./gradlew quarkus:starter:assemble
  test:
    needs: [ setup,build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze with SonarCloud
        run: ./gradlew quarkus:starter:check sonarqube -Dsonar.organization=power-durex-app --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  integrationTest:
    needs: [ setup,test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run integration test
        run: ./gradlew quarkus:starter:integrationTest

