name: Rest-Assured Project Validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/config-action
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: run gradle assemble
        run: ./gradlew springboot:rest-assured:assemble
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Validate Code
        run: ./gradlew springboot:rest-assured:check
  sonar:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - id: sonar_vars
        uses: ./.github/workflows/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew springboot:rest-assured:sonarqube  -Dsonar.organization=power-durex-app  -Dsonar.pullrequest.key=${{ steps.sonar_vars.outputs.sonar_key }} --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  integrationTest:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: run integration test
        run: ./gradlew springboot:rest-assured:integrationTest

