name: Rest-Assured Project
on:
  push:
    branches:
      - master
    paths:
      - 'core/springboot/rest-assured/**'
      - '.github/workflows/rest-assured.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'core/springboot/rest-assured/**'
      - '.github/workflows/rest-assured.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action

  check:
    name: Check Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run gradle assemble
        run: ./gradlew core:springboot:rest-assured:assemble
      - name: Execute Related Check tasks
        run: ./gradlew core:springboot:rest-assured:check
      - name: Validate Code Coverage
        run: ./gradlew core:springboot:rest-assured:jacocoTestCoverageVerification
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: springboot/rest-assured/build
          key:  ${{ runner.os }}-gradle-build-rest-assured-project-${{ github.run_id }}
  sonar:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: springboot/rest-assured/build
          key:  ${{ runner.os }}-gradle-build-rest-assured-project-${{ github.run_id }}
      - id: pr_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew core:springboot:rest-assured:sonarqube  -Dsonar.organization=power-durex-app ${{ steps.pr_vars.outputs.sonar_key }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#  IT:
#    name: Integration Tests
#    runs-on: ubuntu-latest
#    needs: check
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: ./.github/workflows/templates/cache-action
#      - name: Cache build result
#        uses: actions/cache@v2
#        with:
#          path: springboot/rest-assured/build
#          key:  ${{ runner.os }}-gradle-build-rest-assured-project-${{ github.run_id }}
#      - name: run integration test
#        run: ./gradlew core:springboot:rest-assured:IT

