name: Rest-Assured Project Validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: run gradle assemble
        run: ./gradlew springboot:rest-assured:assemble
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Execute Related Check tasks
        run: ./gradlew springboot:rest-assured:check
      - name: Validate Code Coverage
        run: ./gradlew springboot:rest-assured:jacocoTestCoverageVerification
  sonar:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - id: sonar_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew springboot:rest-assured:sonarqube  -Dsonar.organization=power-durex-app ${{ steps.sonar_vars.outputs.sonar_key }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  integrationTest:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/templates/cache-action
      - name: run integration test
        run: ./gradlew springboot:rest-assured:integrationTest

