name: Rest-Assured Project
on:
  push:
    branches:
      - master
    paths:
      - 'core/springboot/rest-assured/**'
      - '.github/workflows/rest-assured.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'core/springboot/rest-assured/**'
      - '.github/workflows/rest-assured.yml'

jobs:
  check:
    name: Check Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
      - name: run gradle assemble
        run: ./gradlew core:springboot:rest-assured:assemble
      - name: Execute Related Check tasks
        run: ./gradlew core:springboot:rest-assured:check
      - name: Validate Code Coverage
        run: ./gradlew core:springboot:rest-assured:jacocoTestCoverageVerification
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: springboot/rest-assured
          key:  ${{ runner.os }}-gradle-build-rest-assured-project-${{ github.run_id }}


