name: Shared Utils Project
on:
  push:
    branches:
      - master
    paths:
      - 'shared/utils/**'
      - '.github/workflows/shared-utils.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'shared/utils/**'
      - '.github/workflows/shared-utils.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
  check:
    name: Check Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run gradle assemble
        run: ./gradlew core:shared:utils:assemble
      - name: Execute Related Check tasks
        run: ./gradlew core:shared:utils:check
      - name: Validate Code Coverage
        run: ./gradlew core:shared:utils:jacocoTestCoverageVerification
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: shared/utils/build
          key:  ${{ runner.os }}-gradle-build-shared-utils-project-${{ github.run_id }}
  sonar:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: shared/utils/build
          key:  ${{ runner.os }}-gradle-build-shared-utils-project-${{ github.run_id }}
      - id: pr_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew core:shared:utils:sonarqube -Dsonar.organization=power-durex-app ${{ steps.pr_vars.outputs.sonar_key }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

