name: Shared Utils Project
on:
  push:
    branches:
      - master
    paths:
      - 'core/shared/utils/**'
      - '.github/workflows/shared-utils.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'core/shared/utils/**'
      - '.github/workflows/shared-utils.yml'

jobs:
  check:
    name: Check Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
      - name: run gradle assemble
        run: ./gradlew core:shared:utils:assemble
      - name: Execute Related Check tasks
        run: ./gradlew core:shared:utils:check
      - name: Validate Code Coverage
        run: ./gradlew core:shared:utils:jacocoTestCoverageVerification
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: shared/utils
          key:  ${{ runner.os }}-gradle-build-shared-utils-project-${{ github.run_id }}

