name: Wire-Mock Project
on:
  push:
    branches:
      - master
    paths:
      - 'springboot/wire-mock/**'
      - '.github/workflows/wire-mock.yml'
  pull_request:
    types: [ opened,reopened, synchronize ]
    paths:
      - 'springboot/wire-mock/**'
      - '.github/workflows/wire-mock.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: run gradle assemble
        run: ./gradlew springboot:wire-mock:assemble
  check:
    name: Check Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run gradle assemble
        run: ./gradlew springboot:wire-mock:assemble
      - name: Execute Related Check tasks
        run: ./gradlew springboot:wire-mock:check
      - name: Validate Code Coverage
        run: ./gradlew springboot:wire-mock:jacocoTestCoverageVerification
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: springboot/wire-mock/build
          key:  ${{ runner.os }}-gradle-build-wire-mock-project
  sonar:
    name: Sonar Analisys
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: springboot/wire-mock/build
          key:  ${{ runner.os }}-gradle-build-wire-mock-project
      - id: pr_vars
        uses: ./.github/workflows/templates/env-action
      - name: Analyze with SonarCloud
        run: ./gradlew springboot:wire-mock:sonarqube  -Dsonar.organization=power-durex-app ${{ steps.pr_vars.outputs.sonar_key }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  IT:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Cache build result
        uses: actions/cache@v2
        with:
          path: springboot/wire-mock/build
          key:  ${{ runner.os }}-gradle-build-wire-mock-project
      - name: run integration test
        run: ./gradlew springboot:wire-mock:integrationTest

