name: Wire-Mock Project Validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened,reopened, synchronize ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/config-action
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: run gradle assemble
        run: ./gradlew springboot:wire-mock:assemble
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/templates/cache-action
      - name: Validate Code
        run: ./gradlew springboot:wire-mock:check
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /home/runner/work/durex/durex/springboot/wire-mock/build/reports/jacoco/test/jacocoTestReport.xml
  integrationTest:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/templates/cache-action
      - name: run integration test
        run: ./gradlew springboot:wire-mock:integrationTest

